/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExpertsRaghuBodduRouteImport } from './routes/experts.raghu-boddu'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpertsRaghuBodduRoute = ExpertsRaghuBodduRouteImport.update({
  id: '/experts/raghu-boddu',
  path: '/experts/raghu-boddu',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/experts/raghu-boddu': typeof ExpertsRaghuBodduRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/experts/raghu-boddu': typeof ExpertsRaghuBodduRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/experts/raghu-boddu': typeof ExpertsRaghuBodduRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/experts/raghu-boddu'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/experts/raghu-boddu'
  id: '__root__' | '/' | '/experts/raghu-boddu'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExpertsRaghuBodduRoute: typeof ExpertsRaghuBodduRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experts/raghu-boddu': {
      id: '/experts/raghu-boddu'
      path: '/experts/raghu-boddu'
      fullPath: '/experts/raghu-boddu'
      preLoaderRoute: typeof ExpertsRaghuBodduRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExpertsRaghuBodduRoute: ExpertsRaghuBodduRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
